MYSQLHOST2 = 'z7hig4hz2hd9.eu-west-2.psdb.cloud'
MYSQLSUER2 = '5s5hurboi23b'
MYSQLPWD2 = 'pscale_pw_KcBiyecK4A9URqgXhBFLuAZhxf8lN2qUeIfs30VDFuo'
MYSQLDB2 = 'garymanleydata'

[snowflake]
user = "KEBOOLA_WORKSPACE_15661914"
password = "Aqris8DKSJ9DcgT9ym2w4GGPw4P5smxE"
account = "keboola.west-europe.azure"
warehouse = "KEBOOLA_PROD"
database = "KEBOOLA_7127"
schema = "WORKSPACE_15661914"

[mysql]
host = "sql4.freesqldatabase.com"
port = 3306
database = "sql4484287"
user = "sql4484287"
password = "b6csh8DiLI"

[planetscale]
host = "z7hig4hz2hd9.eu-west-2.psdb.cloud"
port = 3306
database = "garymanleydata"
user = "5s5hurboi23b"
password = "pscale_pw_KcBiyecK4A9URqgXhBFLuAZhxf8lN2qUeIfs30VDFuo"
connect_args="{'ssl':True}"