WITH w_activities AS (
SELECT 
	 "UPLOAD_ID", 
	"TYPE", 
	TO_DATE(SUBSTR(START_DATE_LOCAL,1,10),'YYYY-MM-DD')	activity_date, 
	distance distance_metres,
	distance/1000 distance_km,
	round(distance/1609,4) distance_miles,	
	moving_time moving_time_seconds,
	round(moving_time/60) moving_time_minutes, 
	TOTAL_ELEVATION_GAIN , 
	AVERAGE_SPEED , 
	AVERAGE_CADENCE, 
	AVERAGE_HEARTRATE, 
	MAX_SPEED , 
	MAX_HEARTRATE 
	
	FROM STG_STRAVA )
SELECT * 
FROM w_activities a
INNER JOIN DATES_DIM D ON a.activity_date = D.date_day
;

SELECT ACTIVITY_DATE , "TYPE",  sum(DISTANCE_KM) distance_km, sum(moving_time_minutes) move_minutes   
FROM STRAVA_ACTIVITIES_STAR_FACT 
WHERE "TYPE" IN ('Run','Walk')
GROUP BY  ACTIVITY_DATE, "TYPE"
;

SELECT UPLOAD_ID,CAST("TYPE" AS STRING) activity_type,ACTIVITY_DATE,DISTANCE_METRES,DISTANCE_KM,DISTANCE_MILES,MOVING_TIME_SECONDS,MOVING_TIME_MINUTES,TOTAL_ELEVATION_GAIN,AVERAGE_SPEED,AVERAGE_CADENCE,AVERAGE_HEARTRATE,MAX_SPEED,MAX_HEARTRATE,DATE_DAY,DATE_YEAR,DATE_MONTH,DATE_QUARTER,DAY_OF_WEEK,DAY_OF_YEAR,WEEK_OF_DAY,DAY_NAME,LAG_DATE_1,YEAR_MONTH FROM STRAVA_ACTIVITIES_STAR_FACT
		